os: windows
language: rust
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_install:
  - rustup component add rustfmt
script:
  - cargo build --verbose --target x86_64-pc-windows-gnu --all
  - cargo test --verbose --target x86_64-pc-windows-gnu --all
  - cargo fmt -- --check
